# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235e572e490459cd7fd9fb6904fedb1c977d64152d99a8c340bbeae023aedb9c7df2e8e763e0f0863c9fcf27f435e14fc67e77844d4aacfda3eb02dafa5f1f7e

test:
  secret_key_base: 84c86d2ce1ae7c46b9667dabc087962a690c5304538b6a149c6c9e829dc8f56f08f84ae4d6e56e679c437dedbd0f82cbe60c06b7a9ebc265caa4b52f5752ca88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
